-- CreateTable
CREATE TABLE "WOO_ORDER_PROCESADA" (
    "orderId" VARCHAR(64) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "WOO_ORDER_PROCESADA_pkey" PRIMARY KEY ("orderId")
);
