-- CreateTable
CREATE TABLE "MOVIMIENTO_CAJA" (
    "id" SERIAL NOT NULL,
    "idCaja" INTEGER NOT NULL,
    "idDepositoOrigen" INTEGER NOT NULL,
    "idDepositoDestino" INTEGER NOT NULL,
    "responsableEnvio" VARCHAR(255) NOT NULL,
    "responsableRecepcion" VARCHAR(255) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "MOVIMIENTO_CAJA_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "MOVIMIENTO_CAJA_idCaja_idx" ON "MOVIMIENTO_CAJA"("idCaja");

-- AddForeignKey
ALTER TABLE "MOVIMIENTO_CAJA" ADD CONSTRAINT "MOVIMIENTO_CAJA_idCaja_fkey" FOREIGN KEY ("idCaja") REFERENCES "CAJA"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
