-- CreateTable
CREATE TABLE "public"."PASSWORD_RESET" (
    "mail" TEXT NOT NULL,
    "tokenHash" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "used" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PASSWORD_RESET_pkey" PRIMARY KEY ("mail")
);

-- AddForeignKey
ALTER TABLE "public"."PASSWORD_RESET" ADD CONSTRAINT "PASSWORD_RESET_mail_fkey" FOREIGN KEY ("mail") REFERENCES "public"."USUARIO"("mail") ON DELETE RESTRICT ON UPDATE CASCADE;
